/**
 * The Real Typography Engine: renders one text layer (title, label,
 * caption — anything that would previously have been baked into an AI
 * image) as a real, vector-rendered, print-ready PNG via `sharp` + SVG.
 * AI never generates lettering; this is the only thing that does.
 */
import sharp from "sharp";
import { ValidationError } from "../../shared/errors.ts";
import { err, ok, type Result } from "../../shared/result.ts";
import { buildTextSvg } from "./svg-text.ts";
import type { TextLayerRequest } from "./types.ts";

/**
 * Average glyph-width-to-font-size ratio for typical sans/serif fonts —
 * a standard estimation technique absent a font-metrics library (see
 * module doc). Real per-glyph measurement would need one (e.g.
 * opentype.js); this trades a little precision for zero new dependencies.
 */
export const AVG_CHAR_WIDTH_RATIO = 0.58;
const MAX_AUTO_FONT_SIZE_PX = 800;

/**
 * Minimum legible font size at this pipeline's print resolution
 * (4500x5400, ~375 DPI for a ~12x14.4in print). This is the engine's
 * answer to "unreadable generated text": since all text is rendered by
 * us, not generated by the AI, legibility is a size floor we enforce at
 * render time rather than something we'd need OCR to detect after the fact.
 */
export const MIN_LEGIBLE_FONT_SIZE_PX = 60;

/** Estimates a font size that fits `text` within `maxWidthPx`, using the average-character-width heuristic. */
export function estimateFontSizeForWidth(
  text: string,
  maxWidthPx: number,
  avgCharWidthRatio: number = AVG_CHAR_WIDTH_RATIO,
): number {
  const effectiveLength = Math.max(text.trim().length, 1);
  const estimated = maxWidthPx / (effectiveLength * avgCharWidthRatio);
  return Math.min(Math.round(estimated), MAX_AUTO_FONT_SIZE_PX);
}

/** Rejects a font size below the legibility floor for this pipeline's print resolution. */
export function validateLegibility(
  fontSizePx: number,
  minLegiblePx: number = MIN_LEGIBLE_FONT_SIZE_PX,
): Result<void, ValidationError> {
  if (fontSizePx < minLegiblePx) {
    return err(
      new ValidationError([
        `font size ${fontSizePx}px is below the minimum legible size of ${minLegiblePx}px at this print resolution`,
      ]),
    );
  }
  return ok(undefined);
}

/**
 * Renders `request` to a transparent PNG buffer at `request.canvasWidthPx`
 * x `request.canvasHeightPx`, suitable for compositing as one layer via
 * the Composition Engine. Auto-sizes when `fontSizePx` is omitted, and
 * always enforces the legibility floor — explicit or auto-fit alike.
 */
export async function renderTextLayer(request: TextLayerRequest): Promise<Result<Buffer, ValidationError>> {
  if (request.text.trim().length === 0) {
    return err(new ValidationError(["text must not be blank"]));
  }

  const fontSizePx =
    request.fontSizePx ?? estimateFontSizeForWidth(request.text, request.maxWidthPx ?? request.canvasWidthPx * 0.8);

  const legibility = validateLegibility(fontSizePx);
  if (!legibility.ok) {
    return legibility;
  }

  const svg = buildTextSvg({ ...request, fontSizePx });

  try {
    const png = await sharp(Buffer.from(svg)).png().toBuffer();
    return ok(png);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return err(new ValidationError([`failed to render text layer: ${message}`]));
  }
}
