/**
 * One-off reconciliation for a Printify product that a previous pipeline run
 * *created* but never finished (the run failed partway through — e.g. the
 * garment-color switch or the Shopify publish step). Per this project's
 * "repair rather than recreate" rule (CLAUDE.md, Phase 4), this completes
 * the existing product instead of creating a second one.
 *
 * Why this can't just be `scripts/regenerate-printify-product.ts`: that
 * script resumes from `designs/published/<stem>.printify.json`, which only
 * exists if a *prior successful* run wrote it. `designs/processed/*.json`
 * (title/description/price generated by the AI step) is gitignored and
 * never committed, so a run that fails after creating the Printify product
 * but before writing that record leaves nothing on disk to resume from —
 * the next checkout (a fresh GitHub Actions runner) has no memory of it.
 *
 * This script instead reads the product's *current* state directly from
 * Printify's own API — title, description, one enabled variant's price, and
 * the artwork image id already attached to its print area — then finishes
 * the two remaining steps (switch to the black variant set, publish to
 * Shopify) using that recovered state.
 *
 * Usage:
 *   node --experimental-strip-types scripts/reconcile-orphan-printify-product.ts <printifyProductId>
 *
 * Requires the same env as a real (DRY_RUN=false) pipeline run: PRINTIFY_API_KEY,
 * PRINTIFY_SHOP_ID, PRINTIFY_BLUEPRINT_ID, PRINTIFY_PRINT_PROVIDER_ID,
 * PRINTIFY_VARIANT_IDS, PRINTIFY_BLACK_VARIANT_IDS.
 */
import { createPrintifyProvider } from "../automation/printify/create-provider.ts";
import { loadEnv } from "../automation/shared/config.ts";

const PRINTIFY_API_BASE = "https://api.printify.com/v1";

interface RawProduct {
  readonly id?: string;
  readonly title?: string;
  readonly description?: string;
  readonly variants?: ReadonlyArray<{ readonly id?: number; readonly price?: number; readonly is_enabled?: boolean }>;
  readonly print_areas?: ReadonlyArray<{
    readonly placeholders?: ReadonlyArray<{ readonly images?: ReadonlyArray<{ readonly id?: string }> }>;
  }>;
}

async function main(): Promise<void> {
  loadEnv();
  const productId = process.argv[2];
  if (productId === undefined || productId.trim().length === 0) {
    console.error(
      "Usage: node --experimental-strip-types scripts/reconcile-orphan-printify-product.ts <printifyProductId>",
    );
    process.exitCode = 1;
    return;
  }

  const shopId = process.env.PRINTIFY_SHOP_ID;
  const apiKey = process.env.PRINTIFY_API_KEY;
  if (shopId === undefined || shopId.trim().length === 0 || apiKey === undefined || apiKey.trim().length === 0) {
    console.error("PRINTIFY_SHOP_ID and PRINTIFY_API_KEY must be set.");
    process.exitCode = 1;
    return;
  }

  const getResp = await fetch(`${PRINTIFY_API_BASE}/shops/${shopId}/products/${productId}.json`, {
    headers: { Authorization: `Bearer ${apiKey}` },
  });
  if (!getResp.ok) {
    console.error(`GET product failed: ${getResp.status} ${await getResp.text()}`);
    process.exitCode = 1;
    return;
  }
  const product = (await getResp.json()) as RawProduct;

  const imageId = product.print_areas?.[0]?.placeholders?.[0]?.images?.[0]?.id;
  const enabledVariant = product.variants?.find((v) => v.is_enabled === true);
  if (
    imageId === undefined ||
    enabledVariant === undefined ||
    enabledVariant.price === undefined ||
    product.title === undefined ||
    product.description === undefined
  ) {
    console.error(
      `Could not recover title/description/imageId/price from the live product ${productId} — aborting ` +
        "rather than guessing. Inspect it by hand in the Printify dashboard.",
    );
    process.exitCode = 1;
    return;
  }
  const priceUsd = enabledVariant.price / 100;

  console.log(`Recovered from live Printify product ${productId}:`);
  console.log(`  title: ${product.title}`);
  console.log(`  description: ${product.description.slice(0, 100)}${product.description.length > 100 ? "..." : ""}`);
  console.log(`  imageId: ${imageId}`);
  console.log(`  priceUsd: ${priceUsd}`);

  const blackVariantIdsRaw = process.env.PRINTIFY_BLACK_VARIANT_IDS;
  if (blackVariantIdsRaw === undefined || blackVariantIdsRaw.trim().length === 0) {
    console.error("PRINTIFY_BLACK_VARIANT_IDS must be set.");
    process.exitCode = 1;
    return;
  }
  const variantIds = blackVariantIdsRaw
    .split(",")
    .map((s) => Number.parseInt(s.trim(), 10))
    .filter((n) => Number.isFinite(n));

  const providerResult = createPrintifyProvider({});
  if (!providerResult.ok) {
    console.error(providerResult.error.message);
    process.exitCode = 1;
    return;
  }
  const printify = providerResult.value;

  const updateResult = await printify.updateProductColorAndPlacement({
    jobId: `reconcile-${productId}`,
    printifyProductId: productId,
    printifyImageId: imageId,
    title: product.title,
    description: product.description,
    priceUsd,
    variantIds,
  });
  if (!updateResult.ok) {
    console.error(`Color-switch update failed: ${updateResult.error.message}`);
    process.exitCode = 1;
    return;
  }
  console.log(`\nSwitched to black variants (${variantIds.length}). New mockup URLs (${updateResult.value.mockupUrls.length}):`);
  for (const url of updateResult.value.mockupUrls) console.log(`  ${url}`);

  const publishResult = await printify.publishProductToShopify({
    jobId: `reconcile-${productId}`,
    printifyProductId: productId,
  });
  if (!publishResult.ok) {
    console.error(`Publish to Shopify failed: ${publishResult.error.message}`);
    process.exitCode = 1;
    return;
  }
  console.log(`\nPublished to Shopify: ${publishResult.value.shopifyProductId} (handle: ${publishResult.value.shopifyHandle ?? "-"})`);

  console.log(
    "\nRECONCILE_RESULT_JSON:" +
      JSON.stringify({
        printifyProductId: productId,
        printifyImageId: imageId,
        title: product.title,
        description: product.description,
        priceUsd,
        variantIds,
        shopifyProductId: publishResult.value.shopifyProductId,
        shopifyHandle: publishResult.value.shopifyHandle,
        mockupUrls: updateResult.value.mockupUrls,
      }),
  );
}

main().catch((error: unknown) => {
  console.error("Unexpected error:", error);
  process.exitCode = 1;
});
